language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: W9p5e0dOOBM5wOnPNR0Fq4zHO9lH/Xx8YZ+dukOktaUYvf0e952w1pcrdOLfhb80w/jJDunrId/5qMHupsYEJ5UW53HjT7Qhz03MKx3ajEpQtEpS0kapF+kBZTQnX7EHNgiG/rHdxptJXnHESd7J/A1Qfhrhrx6Xbog6N7VyuqTQiqr0i5q7VAi7zRiTMajsI3wfzvVwNL4XlsWkW5HFcOY0XhN5Zqth5ztrUVIZIHJ55ZLHEb2i5bJfCg8svHJgixNixugyD7RYH1ItV+egda0BAX72k5gpEPE2QiK7ke/DOsGBfrZcRh9+zow6gyVSkrj1Ob2JZYGdBipBu1VsaY59uObJmC4k2udf9e+7TUgrqiZ1m5ZF5kNwpxd7nQUQesojxq1F3ZRxUggBmaTyz0HSjbCpN05BVmuUtUVHvZ8JTJ5QZGS8xJUJWHHrrAdH6qAetcy+JJ9NiNQE4fWwU7b2zVl9XUd426KJDBl85opqBRLytYBrXpYUyZVgcDkaSgBmdyzeijb5otALIEyXM84e18WSQqjk3fGo51BAhaLpmc6Hi5N/F4zJrc2gMcocmPL1txU9pBAYmNWWSeRe+GvH4QWjcOzcDEtb9mxzRaI1WZUhSsqrr2gnFkkIz7prf7+wSCPLXhK8eMjewY9+ujivFhikL9f0IQ6FMGPbY4E=
  on:
    tags: true
    branch: master
    repo: DEGJS/objectUtils
